services:
  ddns-updater:
    image: ghcr.io/danho-de/ddns-updater:latest
    container_name: ddns-updater
    restart: unless-stopped
    volumes:
      - ./config/config.json:/app/config/config.json:ro
